worldcityList = [
    'Select a city:',
    'Abu Dhabi, UAE',
    'Agra, India',
    'Amman, Jordan',
    'Amsterdam, Netherlands',
    'Antalya, Turkey',
    'Auckland, New Zealand',
    'Baku, Azerbaijan',
    'Bangkok, Thailand',
    'Barcelona, Spain',
    'Beijing, China',
    'Berlin, Germany',
    'Brussels, Belgium',
    'Bucharest, Romania',
    'Budapest, Hungary',
    'Buenos Aires, Argentina',
    'Burgas, Bulgaria',
    'Cairo, Egypt',
    'Cancun, Mexico',
    'Chennai, India',
    'Chiang Mai, Thailand',
    'Christchurch, New Zealand',
    'Delhi, India',
    'Denpasar, Indonesia',
    'Djerba, Tunisia',
    'Doha, Qatar',
    'Dubai, UAE',
    'Dublin, Ireland',
    'East Province, Saudi Arabia',
    'Edirne, Turkey',
    'Florence, Italy',
    'Frankfurt, Germany',
    'Guangzhou, China',
    'Guilin, China',
    'Hangzhou, China',
    'Hanoi, Vietnam',
    'Harare, Zimbabwe',
    'Ho Chi Minh City, Vietnam',
    'Hong Kong, Hong Kong',
    'Honolulu, USA',
    'Istanbul, Turkey',
    'Jaipur, India',
    'Jakarta, Indonesia',
    'Johannesburg, South Africa',
    'Kiev, Ukraine',
    'Kolkata, India',
    'Kuala Lumpur, Malaysia',
    'Las Vegas, USA',
    'Lima, Peru',
    'Lisbon, Portugal',
    'London, UK',
    'Los Angeles, USA',
    'Macau, Macau',
    'Madrid, Spain',
    'Manama, Bahrain',
    'Manila, Philippines',
    'Marrakech, Morocco',
    'Mecca, Saudi Arabia',
    'Melbourne, Australia',
    'Mexico City, Mexico',
    'Miami, USA',
    'Milan, Italy',
    'Moscow, Russia',
    'Mugla, Turkey',
    'Mumbai, India',
    'Munich, Germany',
    'Nairobi, Kenya',
    'Nanjing, China',
    'New York City, USA',
    'Nice, France',
    'Orlando, USA',
    'Paris, France',
    'Pattaya, Thailand',
    'Phuket, Thailand',
    'Prague, Czech Republic',
    'Punta Cana, Dominican Republic',
    'Rio de Janeiro, Brazil',
    'Riyadh, Saudi Arabia',
    'Rome, Italy',
    'San Francisco, USA',
    'Sao Paulo, Brazil',
    'Seoul, South Korea',
    'Shanghai, China',
    'Sharm el-Sheikh, Egypt',
    'Shenzhen, China',
    'Siem Reap, Cambodia',
    'Singapore, Singapore',
    'Sofia, Bulgaria',
    'Sousse, Tunisia',
    'St Petersburg, Russia',
    'Suzhou, China',
    'Sydney, Australia',
    'Taipei City, Taiwan',
    'Tokyo, Japan',
    'Toronto, Canada',
    'Vancouver, Canada',
    'Venice, Italy',
    'Vienna, Austria',
    'Warsaw, Poland',
    'Washington D.C., USA',
    'Zhuhai, China'
]

usaCityList = [
    'Anchorage',
    'Phoenix',
    'Tucson',
    'Mesa',
    'Scottsdale',
    'Chandler',
    'Glendale',
    'Gilbert',
    'Los Angeles',
    'San Diego',
    'San Jose',
    'San Francisco',
    'Fresno',
    'Sacramento',
    'Long Beach',
    'Oakland',
    'Bakersfield',
    'Anaheim',
    'Santa Ana',
    'Riverside',
    'Stockton',
    'Irvine',
    'Chula Vista',
    'Fremont',
    'Denver',
    'Colorado Springs',
    'Aurora',
    'Washington Dc Dc',
    'Jacksonville',
    'Miami',
    'Tampa',
    'Orlando',
    'St. Petersburg',
    'Hialeah',
    'Atlanta',
    'Honolulu',
    'Boise City',
    'Chicago',
    'Indianapolis',
    'Fort Wayne',
    'Wichita',
    'Louisville',
    'Lexington Fayette',
    'New Orleans',
    'Baton Rouge',
    'Baltimore',
    'Boston',
    'Detroit',
    'Minneapolis',
    'St. Paul',
    'Kansas City',
    'St. Louis',
    'Omaha',
    'Lincoln',
    'Las Vegas',
    'Henderson',
    'Reno',
    'North Las Vegas',
    'Newark',
    'Jersey City',
    'Albuquerque',
    'New York',
    'Buffalo',
    'Charlotte',
    'Raleigh',
    'Greensboro',
    'Durham',
    'Winston Salem',
    'Columbus',
    'Cleveland',
    'Cincinnati',
    'Toledo',
    'Oklahoma City',
    'Tulsa',
    'Portland',
    'Philadelphia',
    'Pittsburgh',
    'Nashville',
    'Memphis',
    'Houston',
    'San Antonio',
    'Dallas',
    'Austin',
    'Fort Worth',
    'El Paso',
    'Arlington',
    'Corpus Christi',
    'Plano',
    'Laredo',
    'Lubbock',
    'Irving',
    'Garland',
    'Virginia Beach',
    'Norfolk',
    'Chesapeake',
    'Richmond',
    'Seattle',
    'Spokane',
    'Milwaukee',
    'Madison'    
]

usaCityState = [
    'Alaska',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'Colorado',
    'Colorado',
    'Colorado',
    'District Of Columbia',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Indiana',
    'Kansas',
    'Kentucky',
    'Kentucky',
    'Louisiana',
    'Louisiana',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Minnesota',
    'Missouri',
    'Missouri',
    'Nebraska',
    'Nebraska',
    'Nevada',
    'Nevada',
    'Nevada',
    'Nevada',
    'New Jersey',
    'New Jersey',
    'New Mexico',
    'New York',
    'New York',
    'North Carolina',
    'North Carolina',
    'North Carolina',
    'North Carolina',
    'North Carolina',
    'Ohio',
    'Ohio',
    'Ohio',
    'Ohio',
    'Oklahoma',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Pennsylvania',
    'Tennessee',
    'Tennessee',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Virginia',
    'Virginia',
    'Virginia',
    'Virginia',
    'Washington',
    'Washington',
    'Wisconsin',
    'Wisconsin'
]

var dropdownHtml = "<select>";
console.log("dropdownHtml=" + dropdownHtml);
//--populate country buttons from topics array
for (i=0; i<usaCityList.length; i++) {
    dropdownHtml = dropdownHtml + "<option value='" + usaCityList[i] + "'>" + usaCityState[i] + ": " + usaCityList[i] + "</option>";
};
dropdownHtml = dropdownHtml + "</select>";
console.log("dropdownHtml=" + dropdownHtml);
$("#mainDropdown").append(dropdownHtml);



